site_name: Coveralls for Dart
site_description: Send LCOV and Clover coverage reports to the Coveralls service, in Dart.
site_author: Cédric Belin - cedric@belin.io
site_url: https://dev.belin.io/coveralls.dart

docs_dir: doc
site_dir: web

repo_name: GitHub
repo_url: https://github.com/cedx/coveralls.dart
edit_uri: ''

copyright: Copyright &copy; 2017 - 2018 Cédric Belin
google_analytics:
- !!python/object/apply:os.getenv [GOOGLE_ANALYTICS_ID]
- auto

extra:
  social:
  - {type: globe, link: 'https://belin.io'}
  - {type: github, link: 'https://github.com/cedx'}
  - {type: twitter, link: 'https://twitter.com/cedxbelin'}
  - {type: linkedin, link: 'https://linkedin.com/in/cedxbelin'}

markdown_extensions:
- admonition
- codehilite

pages:
- Overview: index.md
- Installation: installation.md
- Usage:
  - Features: usage/features.md
  - Command line interface: usage/cli.md
  - Programming interface: usage/api.md
- About:
  - Changelog: about/changelog.md
  - License: about/license.md
  - See also: about/see_also.md

theme:
  name: material
  favicon: img/favicon.ico
  palette: {primary: blue, accent: blue}
