name: coveralls
version: 3.0.0

author: CÃ©dric Belin <cedric@belin.io>
description: Send LCOV and Clover coverage reports to the Coveralls service.
documentation: https://cedx.github.io/coveralls.dart
homepage: https://github.com/cedx/coveralls.dart

environment:
  sdk: '>=1.24.0 <2.0.0'

executables:
  coveralls: coveralls

dependencies:
  args: '>=0.13.7 <2.0.0'
  crypto: ^2.0.2
  file: ^2.3.4
  http: ^0.11.3
  lcov: ^3.1.0
  path: ^1.5.0
  platform: ^2.1.1
  where: ^2.2.0
  xml: ^2.6.0
  yaml: ^2.1.13

dev_dependencies:
  coverage: ^0.9.3
  node_preamble: ^1.4.0
  grinder: ^0.8.0
  test: ^0.12.27
